name: Node.js CI
env:
  HOST: 8003
  HOST_TEST: 3006
  DOCKER_USER: '${{ secrets.DOCKER_USER }}'
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  AWS_ACCOUNT_ID: '${{ secrets.AWS_ACCOUNT_ID }}'
  AWS_REGION: '${{ secrets.AWS_REGION }}'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: aws ecr get-login-password --region AWS_REGION | docker login --username AWS --password-stdin AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com | docker run -p 8000:8000 amazon/dynamodb-local
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - run: npm run test:i
