name: Node.js CI
on: [push]

jobs:
  build:
    environment: local-dev
    runs-on: ubuntu-latest
    env:
      HOST: 8003
      HOST_TEST: 3006
      DOCKER_USER: '${{ secrets.DOCKER_USER }}'
      DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
      AWS_ACCOUNT_ID: '${{ secrets.AWS_ACCOUNT_ID }}'
      AWS_REGION: '${{ secrets.AWS_ACCOUNT_ID }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: docker login
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm ci
      - run: docker run -p 8000:8000 amazon/dynamodb-local &
      - run: npm test
      - run: npm run test:i
