name: Node.js CI
env:
  HOST: 8003
  HOST_TEST: 3006

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u ${{ secrets.DOCKER_USER }} $ -p ${{ secrets.DOCKER_PASSWORD }}
          run: docker run -p 8000:8000 amazon/dynamodb-local
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - run: npm run test:i
