name: Node.js CI
env:
  HOST: 8003
  HOST_TEST: 3006

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - run: docker login -u ${{ secrets.DOCKER_USER }} $ -p ${{ secrets.DOCKER_PASSWORD }}
        - run: docker run -p 8000:8000 amazon/dynamodb-local
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - run: npm run test:i
